<a href="https://colab.research.google.com/github/yaryan/PyTorch-Basics/blob/main/Tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
print(torch.__version__)

2.10.0+cpu


In [ ]:
if torch.cuda.is_available():
  print("cuda is available")
  print('Device name: ', torch.cuda.get_device_name(0))
else:
  print("cuda is not available, using CPU")

cuda is not available, using CPU


In [ ]:
# Creating tensors
# Using empty

a = torch.empty(2,3)

In [ ]:
# check type
type(a)

torch.Tensor

In [ ]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# using rand
torch.rand(2,3)

tensor([[0.5295, 0.3436, 0.2514],
        [0.2598, 0.6704, 0.8402]])

In [ ]:
# using seed: it is used to get standard random numbers so reproducibility is possible
torch.rand(2,3)

tensor([[0.3584, 0.4701, 0.0086],
        [0.0151, 0.9796, 0.1280]])

In [ ]:
# manual seed
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [ ]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [ ]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[         0, 1100876160,          0],
        [         0,          0,          0]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x)

NotImplementedError: "check_uniform_bounds" not implemented for 'Long'

## Tensor Data type

In [ ]:
x.dtype

torch.int64

In [ ]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype = torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3], dtype = torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


In [ ]:
torch.rand_like(x, dtype=torch.float64)

tensor([[0.0526, 0.5262, 0.4768],
        [0.9552, 0.9288, 0.0835]], dtype=torch.float64)

## Scalar Operations

In [ ]:
x = torch.rand(2,2)
x

tensor([[0.2666, 0.6274],
        [0.2696, 0.4414]])

In [ ]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.0711, 0.3937],
        [0.0727, 0.1948]])

### 2. Element wise operation

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.2969, 0.8317, 0.1053],
        [0.2695, 0.3588, 0.1994]])
tensor([[0.5472, 0.0062, 0.9516],
        [0.0753, 0.8860, 0.5832]])


In [ ]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[2.9692e-01, 2.6345e-05, 1.0531e-01],
        [4.3697e-02, 3.5881e-01, 1.9936e-01]])

In [ ]:
c = torch.tensor([1, -2, 3, -4])

In [ ]:
# abs val
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [ ]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [ ]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction operation

In [ ]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[3., 4., 9.],
        [6., 2., 0.]])

In [ ]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([16.,  8.])

In [ ]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([4.5000, 3.0000, 4.5000])

In [ ]:
# median
torch.median(e)

tensor(3.)

In [ ]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [ ]:
# product
torch.prod(e)

tensor(0.)

In [ ]:
# standard deviation
torch.std(e)

tensor(3.1623)

In [ ]:
# variance
torch.var(e)

tensor(10.)

In [ ]:
# argmax
torch.argmax(e)

tensor(2)

In [ ]:
# argmin
torch.argmin(e)

tensor(5)

### 4. Matrix operations

In [ ]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[6, 2, 7],
        [9, 7, 3]])
tensor([[3, 4],
        [3, 7],
        [0, 9]])


In [ ]:
torch.matmul(f,g)

tensor([[ 24, 101],
        [ 48, 112]])

In [ ]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [ ]:
f

tensor([[6, 2, 7],
        [9, 7, 3]])

In [ ]:
# transpose
torch.transpose(f, 0, 1)

tensor([[6, 9],
        [2, 7],
        [7, 3]])

In [ ]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[0., 9., 6.],
        [9., 5., 4.],
        [8., 8., 6.]])

In [ ]:
# determinant
torch.det(h)

tensor(-6.0000)

In [ ]:
# inverse
torch.inverse(h)

tensor([[  0.3333,   1.0000,  -1.0000],
        [  3.6667,   8.0000,  -9.0000],
        [ -5.3333, -12.0000,  13.5000]])

In [ ]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[0, 0, 0],
        [0, 1, 3]])
tensor([[0, 1, 1],
        [7, 9, 4]])


In [ ]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[False,  True,  True],
        [ True,  True,  True]])

## Inplace Operations

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.0874, 0.0041, 0.1088],
        [0.1637, 0.7025, 0.6790]])
tensor([[0.9155, 0.2418, 0.1591],
        [0.7653, 0.2979, 0.8035]])


In [ ]:
 m.add_(n)

tensor([[1.0028, 0.2458, 0.2680],
        [0.9289, 1.0004, 1.4825]])

In [ ]:
m

tensor([[1.0028, 0.2458, 0.2680],
        [0.9289, 1.0004, 1.4825]])

In [ ]:
n

tensor([[0.9155, 0.2418, 0.1591],
        [0.7653, 0.2979, 0.8035]])

In [ ]:
torch.relu(m)

tensor([[1.0028, 0.2458, 0.2680],
        [0.9289, 1.0004, 1.4825]])

In [ ]:
m.relu_()

tensor([[1.0028, 0.2458, 0.2680],
        [0.9289, 1.0004, 1.4825]])

In [ ]:
m

tensor([[1.0028, 0.2458, 0.2680],
        [0.9289, 1.0004, 1.4825]])

## Copying a Tensor

In [ ]:
a = torch.rand(2,3)
a

tensor([[0.3813, 0.7860, 0.1115],
        [0.2477, 0.6524, 0.6057]])

In [ ]:
a[0][0] = 0

In [ ]:
b = a

In [ ]:
a

tensor([[0.0000, 0.7860, 0.1115],
        [0.2477, 0.6524, 0.6057]])

In [ ]:
b

tensor([[0.0000, 0.7860, 0.1115],
        [0.2477, 0.6524, 0.6057]])

In [ ]:
id(a)

136947201007824

In [ ]:
id(b)

136947201007824

In [ ]:
b = a.clone()

In [ ]:
a

tensor([[0.0000, 0.7860, 0.1115],
        [0.2477, 0.6524, 0.6057]])

In [ ]:
b

tensor([[0.0000, 0.7860, 0.1115],
        [0.2477, 0.6524, 0.6057]])

In [ ]:
a[0][0]= 10

In [ ]:
a

tensor([[10.0000,  0.7860,  0.1115],
        [ 0.2477,  0.6524,  0.6057]])

In [ ]:
b

tensor([[0.0000, 0.7860, 0.1115],
        [0.2477, 0.6524, 0.6057]])

In [ ]:
id(a)

136947201007824

In [ ]:
id(b)

136946220835024